/**
 * Expo config plugin — withHealthConnectManifest
 *
 * react-native-health-connect's own Expo plugin only injects
 * ACTION_SHOW_PERMISSIONS_RATIONALE into MainActivity. It does NOT add:
 *
 *   1. android.permission.health.READ_STEPS — required for the system to
 *      know the app uses Health Connect at all.
 *
 *   2. The <queries> entries — required so the app can query Health Connect's
 *      package availability and send intents to it.
 *
 *   3. The <activity-alias> with VIEW_PERMISSION_USAGE + HEALTH_PERMISSIONS —
 *      required for APEX to appear in Health Connect's "Apps" list so the
 *      user can grant Steps permission. Without this the app is invisible in HC.
 *
 * Because android/ is gitignored (generated by expo prebuild), any manual edits
 * to AndroidManifest.xml are wiped on every EAS build. This plugin ensures the
 * entries survive by injecting them at prebuild time.
 */

const { withAndroidManifest } = require('@expo/config-plugins');

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withHealthConnectManifest = (config) =>
  withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    // ── 1. Permission ──────────────────────────────────────────────────────────
    if (!manifest['uses-permission']) manifest['uses-permission'] = [];

    const hasStepsPermission = manifest['uses-permission'].some(
      (p) => p.$?.['android:name'] === 'android.permission.health.READ_STEPS',
    );
    if (!hasStepsPermission) {
      manifest['uses-permission'].push({
        $: { 'android:name': 'android.permission.health.READ_STEPS' },
      });
    }

    // ── 2. <queries> entries ───────────────────────────────────────────────────
    if (!manifest.queries) manifest.queries = [];

    const hasHcPackage = manifest.queries.some((q) =>
      (q.package ?? []).some((p) => p.$?.['android:name'] === 'com.google.android.apps.healthdata'),
    );
    if (!hasHcPackage) {
      manifest.queries.push({
        package: [{ $: { 'android:name': 'com.google.android.apps.healthdata' } }],
        intent: [
          {
            action: [{ $: { 'android:name': 'androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE' } }],
          },
        ],
      });
    }

    // ── 3. <activity-alias> — makes APEX visible in Health Connect ─────────────
    const application = manifest.application[0];
    if (!application['activity-alias']) application['activity-alias'] = [];

    const hasAlias = application['activity-alias'].some(
      (a) => a.$?.['android:name'] === 'ViewPermissionUsageActivity',
    );
    if (!hasAlias) {
      application['activity-alias'].push({
        $: {
          'android:name': 'ViewPermissionUsageActivity',
          'android:exported': 'true',
          'android:targetActivity': '.MainActivity',
          'android:permission': 'android.permission.START_VIEW_PERMISSION_USAGE',
        },
        'intent-filter': [
          {
            action: [{ $: { 'android:name': 'android.intent.action.VIEW_PERMISSION_USAGE' } }],
            category: [{ $: { 'android:name': 'android.intent.category.HEALTH_PERMISSIONS' } }],
          },
        ],
      });
    }

    return mod;
  });

module.exports = withHealthConnectManifest;
